mensagem = input('Digite algo: ')
print(f'Tipo: {type(mensagem)}')
print(f'A sua mensagem é alfanúmerica? {mensagem.isalnum()}')
print(f'A sua mensagem é somente númerica? {mensagem.isnumeric()}')
print(f'A sua mensagem é somente alfabetica? {mensagem.isalpha()}')
print(f'A sua mensagem está capitalizada? {mensagem.istitle()}')
print(f'A sua mensagem está somente em letras minúsculas? {mensagem.islower()}')
print(f'A sua mensagem está somente em letras maiúsculas? {mensagem.isupper()}')
print(f'A sua mensagem contém apenas espaços? {mensagem.isspace()}')